plugins:
  - "@typescript-eslint/eslint-plugin"

settings:
  import/extensions: [.js, .jsx, .ts, .tsx]
  import/parsers:
    "@typescript-eslint/parser": [.ts, .tsx]

overrides:
  - files: ["**/*.ts", "**/*.tsx"]
    extends:
      - plugin:@typescript-eslint/recommended
    parser: "@typescript-eslint/parser"
    settings:
      import/resolver: typescript

rules:
  "@typescript-eslint/no-unused-vars": [2, {vars: all, args: all, caughtErrors: all, ignoreRestSiblings: false, argsIgnorePattern: ^_, varsIgnorePattern: "^_[^_]*$", caughtErrorsIgnorePattern: ^_, destructuredArrayIgnorePattern: ^_}]
